D5ng/team-mogazoa-sprint

src/app/styles/globals.css
=> ♻️ [#19] Refactor: globals 위치 변경

package.json, yarn.lock
=> 📦 Chore: TanstackQuery, Axios 패키지 추가

pages/sign-up/index.tsx, pages/wow/index.tsx, src/app/styles/globals.css, src/shared/hooks/index.ts, src/shared/hooks/useAutoComplete.ts, src/shared/ui/autocompleteSuggestions/AutocompleteSuggestions.tsx, src/shared/ui/autocompleteSuggestions/AutocompleteSuggestions.type.ts, src/shared/ui/form-field/FormField.tsx, src/shared/ui/text-field-input/TextFieldInput.tsx, src/shared/ui/text-field-input/TextFieldInput.type.ts, yarn.lock
> #28
https://github.com/user-attachments/assets/e0460c8b-5806-4123-848d-a299a2c8ed4a
> - 여러 페이지와 모달에 사용되는 TextFieldInput 컴포넌트를 제작하였습니다.
> - 검색 input에도 사용할 수 있도록 useAutocomplete이라는 훅을 제작하였습니다.
> - 동현님이 만드신 useToggle, useOutsideClick 훅을 사용하여 코드 수를 줄였습니다.
> - debounce 기능을 넣어 성능 개선과 사용자 경험을 높였습니다.
> - Icon 컴포넌트가 완성되면 input의 버튼을 변경하겠습니다.
> - 여전히 코드를 깔끔하게 분리하는 게 쉽지 않네요. 개선할 부분이 있다면 가감없이 말씀부탁드립니다.
=> ✨ Feat: TextFiledInput 컴포넌트 및 자동완성 기능

src/shared/ui/dropdown/Dropdown.constants.ts, src/shared/ui/dropdown/Dropdown.tsx, src/shared/ui/dropdown/Dropdown.type.ts
=> 🐛 Fix: Dropdown 버그

src/shared/ui/button/Button.tsx
=> ✨ Feat: Button 반응형 추가

src/shared/ui/dropdown/Dropdown.constants.ts
=> ✨ Feat: Dropdown 반응형 추가

src/widgets/product-review-modal/components/form/ReviewCreateForm.tsx, src/widgets/product-review-modal/components/form/ReviewUpdateForm.tsx
#102 
ReactHookForm에서 onBlur로 처리되어있어서 유효성 검증이 되어도 버튼이 활성화 되지않는 문제.
>
=> 🐛 Fix: Product-review-modal 사용성 문제.

middleware.ts
=> ✨ Feat: 페이지 접근 권한 보호

src/shared/api/user.api.ts, src/shared/hooks/mutate/follow.mutate.ts, src/shared/hooks/mutate/user.mutate.ts, src/shared/hooks/query-keys/index.ts, src/shared/hooks/query-keys/user.key.ts, src/shared/hooks/query/user.query.ts, src/shared/types/user/user.type.ts, src/widgets/profile/components/activity-log-section/ActivityLogSection.tsx, src/widgets/profile/components/product-card-section/products/CreatedProducts.tsx, src/widgets/profile/components/product-card-section/products/FavoriteProducts.tsx, src/widgets/profile/components/product-card-section/products/ProductsList.tsx, src/widgets/profile/components/product-card-section/products/ReviewedProducts.tsx, src/widgets/profile/components/product-card-section/section/ProductCardSection.tsx, src/widgets/profile/components/profile-card/card-contents/FolloweesButton.tsx, src/widgets/profile/components/profile-card/card-contents/FollowerButton.tsx, src/widgets/profile/components/profile-card/card-contents/ProfileStats.tsx, src/widgets/profile/components/profile-follow-modal/followees-list/FolloweesList.tsx, src/widgets/profile/components/profile-follow-modal/follower-list/FollowerList.tsx, src/widgets/profile/components/profile-follow-modal/modal/ProfileFolloweesModal.tsx, src/widgets/profile/components/profile-follow-modal/modal/ProfileFollowerModal.tsx
=> ♻️ Refactor: user 쿼리 키 정리

pages/404.tsx, pages/_app.tsx, pages/index.tsx, pages/product/[id]/index.tsx, src/pages/product/Product.tsx, src/shared/hooks/useToggle.ts, src/shared/ui/gnb/Gnb.tsx, src/shared/ui/gnb/GnbMenu.tsx, src/shared/ui/gnb/GnbMobileSideBar.tsx, src/shared/ui/product-card/ProductCardItem.tsx, src/widgets/product/product-home/components/category-menu/CategoryMenu.tsx, src/widgets/product/product-home/components/ranking/Ranking.tsx
=> ♻️ refactor: categoryMenu 분리, 메인페이지 ui 수정, 로그인에 따른 menu 분기처리

pages/category/[id]/index.tsx, pages/product/category/[id]/index.tsx, src/pages/index.ts, src/pages/product/category/ProductCategoryPage.tsx, src/shared/ui/category-chip/CategoryChip.type.ts, src/shared/ui/product-card/ProductCardList.tsx, src/widgets/product/product-home/components/category-menu/CategoryItems.tsx, src/widgets/product/product-home/components/category-menu/CategoryMenu.tsx, src/widgets/product/product-home/components/index.ts, src/widgets/product/product-home/components/product-empty/ProductEmpty.tsx
=> ✨ Feat: 카테고리 페이지 추가

pages/product/[id]/index.tsx, pages/product/category/[id]/index.tsx, pages/profile/[id]/index.tsx, pages/profile/my/index.tsx
=> ✨ Feat: 헤더 인증에 따른 메뉴 보여주기

.storybook/main.ts, .storybook/preview-body.html, .storybook/preview.tsx, package.json, public/mockServiceWorker.js, src/app/styles/stories.css, src/shared/hooks/useImageFallback.ts, src/shared/types/product/product.type.ts, src/shared/ui/product-card/ProductCardItem.mdx, src/shared/ui/product-card/ProductCardItem.stories.tsx, src/shared/ui/product-card/ProductCardItem.tsx, src/shared/ui/product-card/ProductCardSkeleton.stories.tsx, src/shared/ui/profile-image/ProfileImage.tsx, src/widgets/product/product-home/components/product-hot/ProductListExample.stories.tsx, src/widgets/product/product-home/components/ranking/Ranking.mdx, src/widgets/product/product-home/components/ranking/Ranking.stories.tsx, src/widgets/product/product-home/components/ranking/Ranking.tsx, src/widgets/product/product-home/components/ranking/RankingItem.stories.tsx, src/widgets/product/product-home/components/ranking/RankingItem.tsx, src/widgets/product/product-home/storybook/ProductModal.stories.tsx, tsconfig.json, yarn.lock
=> 💄 storybook : ranking, productCard mdx 작성

.storybook/preview.tsx, src/widgets/product/product-detail/components/review-modal/modal/ReviewCreateModal.stories.tsx
=> ✨ Feat: 리뷰 생성 모달 스토리북

.storybook/preview.tsx, src/widgets/product/product-detail/components/review-modal/modal/ReviewCreateModal.stories.tsx, src/widgets/product/product-detail/components/review-modal/modal/ReviewUpdateModal.stories.tsx
=> ✨ Feat: 리뷰 업데이트 모달 스토리북

src/widgets/product/common/category-dropdown/CategoryDropdown.stories.tsx, src/widgets/product/common/sort-dropdown/SortDropdown.stories.tsx
=> ♻️ Refactor: 스토리북 구조 리팩토링

src/shared/ui/modal/Modal.mdx, src/shared/ui/modal/Modal.stories.tsx, src/widgets/product/product-home/components/product-create-modal/modal/ProductCreateModal.stories.tsx
=> ✨ Feat: 모달 스토리북 추가

src/shared/mocks/index.ts, src/shared/mocks/product/index.tsx, src/shared/mocks/review/index.ts, src/shared/mocks/upload/index.tsx, src/widgets/product/product-detail/components/product-update-modal/modal/ProductUpdateModal.stories.tsx, src/widgets/product/product-detail/components/review-modal/modal/ReviewCreateModal.stories.tsx, src/widgets/product/product-detail/components/review-modal/modal/ReviewUpdateModal.stories.tsx, src/widgets/product/product-home/components/product-create-modal/modal/ProductCreateModal.stories.tsx, tsconfig.json
=> ✨ Feat: MSW Handler 관리하는 mock 폴더 추가

src/shared/ui/dropdown/Dropdown.tsx, src/shared/ui/input/textarea-input/TextareaInput.tsx, src/widgets/product/product-detail/components/review-modal/form/ReviewCreateForm.tsx, src/widgets/product/product-detail/components/review-modal/form/ReviewUpdateForm.tsx, src/widgets/product/product-home/components/ranking/Ranking.tsx
=> 💄Design: 스크롤바 커스텀으로 변경 또는 스크롤바 ui 없애기

.storybook/preview.tsx, src/shared/mocks/review/index.ts, src/widgets/product/product-detail/components/review/Review.stories.tsx, src/widgets/product/product-detail/components/review/contents/ReviewContents.tsx
=> ✨ Feat: 리뷰 스토리북

src/widgets/product/product-detail/components/review/Review.stories.tsx
=> 🔥 Remove: 스토리북 불필요한 코드 제거

src/app/styles/globals.css, src/shared/ui/button/Button.constants.ts, src/shared/ui/button/Button.mdx, src/shared/ui/button/Button.stories.tsx, src/shared/ui/button/Button.tsx, src/shared/ui/loading/Loading.tsx, src/widgets/product/product-detail/components/review/Review.stories.tsx, tailwind.config.ts
=> ✨ Feat: UI Button States 추가

pages/profile/[id]/index.tsx, src/pages/profile/Profile.tsx, src/shared/hooks/index.ts, src/shared/hooks/useClientSide.ts, src/shared/ui/autocomplete-field/AutocompleteField.type.ts, src/shared/ui/category-chip/CategoryChip.constants.ts, src/shared/ui/category-chip/CategoryChip.tsx, src/shared/ui/product-card/ProductCardItem.tsx, src/widgets/profile/components/activity-log-section/LogList.tsx, src/widgets/profile/components/activity-log-section/LogListItem.tsx, src/widgets/profile/components/profile-card/card/MyProfileCard.tsx, src/widgets/profile/components/profile-card/card/UserProfileCard.tsx, src/widgets/profile/components/profile-follow-modal/follow/Follow.tsx
=> 🐛 Fix: 프로필 페이지 관련 에러 해결

src/pages/product/Product.tsx, src/shared/types/user/user.type.ts, src/shared/ui/product-card/ProductCardItem.tsx, src/widgets/product/product-detail/components/product-info/product-contents/LikeButton.tsx, src/widgets/product/product-detail/components/product-info/product-image/ProductImage.tsx, src/widgets/product/product-detail/components/review/contents/ReviewContents.tsx, src/widgets/product/product-home/components/product-hot/ProductHot.tsx, src/widgets/product/product-home/layout/ProductCardSection.tsx, src/widgets/profile/components/activity-log-section/ActivityLogSection.tsx, src/widgets/profile/components/profile-follow-modal/follow/Follow.tsx, src/widgets/profile/components/profile-follow-modal/followees-list/FolloweesList.tsx, src/widgets/profile/components/profile-follow-modal/follower-list/FollowerList.tsx, src/widgets/profile/components/profile-follow-modal/modal/ProfileFolloweesModal.tsx, src/widgets/profile/components/profile-follow-modal/modal/ProfileFollowerModal.tsx
=> 🐛 Fix: 전반적인 에러 수정

src/shared/types/user/user.type.ts, src/widgets/profile/components/profile-follow-modal/followees-list/FolloweesList.tsx, src/widgets/profile/components/profile-follow-modal/follower-list/FollowerList.tsx
=> 🐛 Fix: 타입 에러 해결

pages/_document.tsx
=> 🐛 [#199] Fix: 파비콘 안나오는 문제 해결

src/app/styles/globals.css, src/pages/product/Product.tsx, src/shared/hooks/query/product.query.ts, src/shared/ui/gnb/GnbMobileSideBar.tsx, src/widgets/product/product-home/components/product-searched/index.tsx
=> 🐛fix: 메인페이지 api 요청 중복 제거

pages/index.tsx
=> 성능테스트 - data를 클라이언트 측에서 로드

src/widgets/product/product-detail/components/review/contents/ReviewContents.tsx
=> 🐛 Fix: Review 수정 시 날짜 바뀌는 문제.

.gitignore, package.json, yarn.lock
=> 📦 Chore: 스토리북 패키지 추가

pages/_app.tsx, pages/api/kakao/signUp.tsx, src/pages/auth/sign-in/SignInPage.tsx, src/pages/auth/sign-up/SignUpPage.tsx, src/shared/constants/social.constants.ts, src/shared/ui/input/image-input/ImageInput.tsx, src/widgets/auth/components/sign-in-field/SignInField.tsx, src/widgets/auth/components/sign-up-field/SignUpField.tsx, src/widgets/profile/components/profile-edit-modal/form/ProfileEditForm.tsx, src/widgets/profile/components/profile-edit-modal/image-upload/ProfileImageUpload.tsx, src/widgets/profile/components/profile-follow-modal/followees-list/FolloweesList.tsx, src/widgets/profile/components/profile-follow-modal/follower-list/FollowerList.tsx
=> 🐛 Fix: 프로필 수정 사항 및 기타 에러 해결

src/widgets/product/product-home/hooks/useProductAddForm.ts
=> 🐛 Fix: 상품 추가 모달 로딩 처리

src/widgets/auth/components/oauth-sign-up-field/OauthSignUpField.tsx, src/widgets/product/product-detail/components/review-modal/image-upload/ReviewImageUpload.tsx, src/widgets/product/product-detail/hooks/useUpdateReviewForm.ts, src/widgets/product/product-home/hooks/useProductAddForm.ts
=> 🐛 Fix: 리뷰 수정 모달 이미지 버그.

src/pages/product/category/ProductCategoryPage.tsx, src/widgets/auth/components/oauth-sign-up-field/OauthSignUpField.tsx, src/widgets/product/common/category-dropdown/CategoryDropdown.stories.tsx, src/widgets/product/product-detail/components/review-modal/image-upload/ReviewImageUpload.tsx, src/widgets/product/product-detail/hooks/useUpdateReviewForm.ts, src/widgets/product/product-home/components/product-create-modal/form/ProductCreateForm.tsx, src/widgets/product/product-home/components/product-create-modal/form/defaultValues.ts, src/widgets/product/product-home/components/product-create-modal/modal/ProductCreateModal.tsx, src/widgets/product/product-home/components/product-empty/ProductEmpty.tsx, src/widgets/product/product-home/hooks/useProductAddForm.ts
=> 🐛 Fix: 빈 카테고리 페이지에서 추가 시 기본 카테고리 지정

src/widgets/product/product-home/components/product-empty/ProductEmpty.tsx
=> 🐛 [#248] Fix: 상품 비어있을 때 메세지 출력

src/shared/ui/dropdown/Dropdown.tsx, src/shared/ui/modal/Modal.tsx, src/widgets/product/product-detail/components/product-update-modal/form/ProductUpdateForm.tsx, src/widgets/product/product-home/components/product-create-modal/form/ProductCreateForm.tsx, src/widgets/product/product-home/components/product-empty/ProductEmpty.tsx
=> 🐛 Fix: 모바일에서 모달 사이즈가 큰 문제

src/shared/ui/gnb/Gnb.stories.ts, src/shared/ui/gnb/Gnb.tsx, src/shared/ui/product-card/ProductCardSkeleton.stories.tsx, src/widgets/product/product-home/components/category-menu/SideMenu.stories.ts, src/widgets/product/product-home/components/product-hot/ProductListExample.stories.tsx, src/widgets/product/product-home/components/ranking/Ranking.stories.tsx, src/widgets/product/product-home/components/ranking/RankingItem.stories.tsx
=> ♻️ Refactor: 스토리북 카테고리 분류하기

src/shared/ui/gnb/Gnb.stories.ts, src/shared/ui/gnb/Gnb.tsx
=> 🐛 Fix: Gnb 스타일 에러

src/widgets/product/product-detail/components/product-delete-modal/ProductDeleteModal.tsx, src/widgets/product/product-detail/hooks/useUpdateProductForm.ts
=> ✨ Feat: 상품 수정, 상품 삭제 토스트 추가

src/shared/ui/category-chip/CategoryChip.constants.ts
=> 🐛 Fix: 카테고리 데이터 안 맞는 부분 수정

src/shared/ui/button/Button.stories.tsx
=> ✨ Feat: 버튼 스토리북 컨트롤 추가

src/shared/ui/category-chip/CategoryChip.stories.tsx, src/shared/ui/dropdown/Dropdown.stories.tsx
#273 
모달 관련해서 스토리북의 컨트롤을 이용해 연동하고 싶었지만 리액트 훅 폼은 비제어로 진행되기에,, 수정이 잘 안되는 문제가 생겼습니다
>
=> ✨ Feat: 스토리북 컨트롤 추가
